# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jig < Formula
  desc "Claude Code session configurator — manage profiles, MCP servers, and launch settings via a terminal UI"
  homepage "https://github.com/jdforsythe/jig"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdforsythe/jig/releases/download/v0.1.0/jig_darwin_amd64.tar.gz"
      sha256 "0e4a72648f2291cc8c8f1e8b8a2b3eea1e6d4376b996e3e97958a6f18b697153"

      define_method(:install) do
        bin.install "jig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdforsythe/jig/releases/download/v0.1.0/jig_darwin_arm64.tar.gz"
      sha256 "3192cf2e3e732747917efa915a8eca047def7040310b2f8034e3efd2ab4a6d64"

      define_method(:install) do
        bin.install "jig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdforsythe/jig/releases/download/v0.1.0/jig_linux_amd64.tar.gz"
      sha256 "6faf6999068a714c7575244f4a240ffecc5c3f09483bd702e5a8ec39dc814826"
      define_method(:install) do
        bin.install "jig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdforsythe/jig/releases/download/v0.1.0/jig_linux_arm64.tar.gz"
      sha256 "d64a7c76abe861edde2eeb529646ee99fff69a7ba77a9bc70447f5fab8d036a3"
      define_method(:install) do
        bin.install "jig"
      end
    end
  end

  test do
    system "#{bin}/jig --version"
  end
end
