# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jig < Formula
  desc "Claude Code session configurator — manage profiles, MCP servers, and launch settings via a terminal UI"
  homepage "https://github.com/jdforsythe/jig"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdforsythe/jig/releases/download/v0.1.1/jig_darwin_amd64.tar.gz"
      sha256 "38ff91a324ad3fa3beed63a36802901607742a254d05a613724c1f7ee9dec76f"

      define_method(:install) do
        bin.install "jig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdforsythe/jig/releases/download/v0.1.1/jig_darwin_arm64.tar.gz"
      sha256 "0f94c689d8fd17a15bea0efd938a284c0a1d701fd79c71e6154b2b823630a352"

      define_method(:install) do
        bin.install "jig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdforsythe/jig/releases/download/v0.1.1/jig_linux_amd64.tar.gz"
      sha256 "aaf8cbd82276b784cd68a50e40911a6b84e7d582f3f9cafd1cb70d914c17f7cc"
      define_method(:install) do
        bin.install "jig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdforsythe/jig/releases/download/v0.1.1/jig_linux_arm64.tar.gz"
      sha256 "9126980f0c6fbb1cc1682126211d6ad0eae472eb872772b3ae6e174141d4a743"
      define_method(:install) do
        bin.install "jig"
      end
    end
  end

  test do
    system "#{bin}/jig --version"
  end
end
